# raise TypeError
raise TypeError('aaaa has a except')